soundfiles:
    startup: /home/pi/ringtones/startup1.wav
    shutdown: /home/pi/ringtones/shutdown1.wav
    ringtone: /home/pi/ringtones/aselektriskbureau.wav
    busytone: /home/pi/ringtones/Old_North_American_busy_signal.wav
    timeout: /home/pi/ringtones/roh.wav
    dialtone: /home/pi/ringtones/dialtone.wav

sip:
    username: siemens1
    password: AXtCCDMApsVUcTFw
    hostname: fritz.box
    port: 5060
